stages:
  - build
  - deploy

build-task-service:
  stage: build
  script:
    - docker build -t task_app hw_02/task_service/.
  only:
    - hw_02

build-user-service:
  stage: build
  script:
    - docker build -t user_app hw_02/user_service/.
  only:
    - hw_02

deploy-job:
  stage: deploy
  script:
    - docker compose up --build -d
  only:
    - hw_02