stages:
  - build
  - deploy

build-task-service:
  stage: build
  script:
    - docker build -t task_app hw_04/task_service/.
  only:
    - main

build-user-service:
  stage: build
  script:
    - docker build -t user_app hw_04/user_service/.
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - docker compose up --build -d
  only:
    - main